### ISSUE TITLE
Update Docker installation instruction for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by e2themillions** [odk-x/tool-suite-X#177]
It appears that docker can no longer (since yesterday!) be installed using the current instructions (i.e. by adding version specific Docker repository to apt) on Ubuntu 20.04 (Focal Fossa). According to askubuntu the release file for Docker is no longer available. On 20.04 it can either be installed using the Bionic repository or simply by "apt install docker.io". I am not sure of the reasons why nor the implications, but the instructions should probably be updated..

**Comment by starboi02** [comment]
Can I work on it?

**Comment by wbrunette** [comment]
@starboi02 I have assigned the issue to you.

**Comment by linl33** [comment]
@starboi02 Could you give us an update on this issue? Let us know if you have any questions.

**Comment by starboi02** [comment]
@linl33 This issue is not relevant now because the release file of docker for Ubuntu 20.04 LTS (Focal Fossa) is available now. So there is no need to change the documentation anywhere since it has been resolved. Here's the [link](https://askubuntu.com/questions/1230189/how-to-install-docker-community-on-ubuntu-20-04-lts#:~:text=sudo%20add%2Dapt%2Drepository%20%5C,%5B265%20kB%5D%20Ign%3A3) to the askubuntu forum where it is stated that the release file is now available.  And I have cross checked it. So you can close the issue.

**Comment by e2themillions** [comment]
Thanks for clarifying. I'm closing the issue now 👍
